# Generated by Django 5.0.13 on 2025-12-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id_deporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_deporte', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('num_jugadores_equipo', models.IntegerField()),
                ('es_individual', models.BooleanField()),
                ('reglas_basicas', models.TextField()),
                ('tipo_superficie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id_deportista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('deporte_principal', models.CharField(max_length=50)),
                ('nivel_habilidad', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('lesiones_previas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion_Deportiva',
            fields=[
                ('id_instalacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_instalacion', models.CharField(max_length=255)),
                ('tipo_instalacion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad_personas', models.IntegerField()),
                ('costo_alquiler_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_techada', models.BooleanField()),
                ('horario_disponible', models.TextField()),
                ('descripcion_equipamiento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
                ('entrenador', models.CharField(max_length=100)),
                ('capitan', models.CharField(max_length=100)),
                ('num_jugadores_actual', models.IntegerField()),
                ('categoria_edad', models.CharField(max_length=50)),
                ('colores_equipo', models.CharField(max_length=50)),
                ('deporte', models.ForeignKey(db_column='id_deporte', on_delete=django.db.models.deletion.PROTECT, to='app_CentroDeportivo.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion_Equipo',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('rol_en_equipo', models.CharField(max_length=50)),
                ('num_camiseta', models.IntegerField()),
                ('es_titular', models.BooleanField()),
                ('fecha_baja_equipo', models.DateField(blank=True, null=True)),
                ('deportista', models.ForeignKey(db_column='id_deportista', on_delete=django.db.models.deletion.CASCADE, to='app_CentroDeportivo.deportista')),
                ('equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='app_CentroDeportivo.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_partido', models.DateField()),
                ('hora_partido', models.TimeField()),
                ('lugar_partido', models.CharField(max_length=100)),
                ('resultado_local', models.IntegerField()),
                ('resultado_visitante', models.IntegerField()),
                ('arbitro', models.CharField(max_length=100)),
                ('deporte', models.ForeignKey(db_column='id_deporte', on_delete=django.db.models.deletion.PROTECT, to='app_CentroDeportivo.deporte')),
                ('equipo_local', models.ForeignKey(db_column='id_equipo_local', on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='app_CentroDeportivo.equipo')),
                ('equipo_visitante', models.ForeignKey(db_column='id_equipo_visitante', on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='app_CentroDeportivo.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Instalacion',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('motivo_reserva', models.TextField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_reserva', models.CharField(max_length=50)),
                ('deportista', models.ForeignKey(db_column='id_deportista_reserva', on_delete=django.db.models.deletion.CASCADE, to='app_CentroDeportivo.deportista')),
                ('instalacion', models.ForeignKey(db_column='id_instalacion', on_delete=django.db.models.deletion.PROTECT, to='app_CentroDeportivo.instalacion_deportiva')),
            ],
        ),
    ]
